services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    restart: unless-stopped
    # Uncomment the following lines for live code reload in development
    # volumes:
    #   - ./backend:/usr/src/app
    #   - /usr/src/app/node_modules
